function Rim = KT_gen_convol_spv(omega,Orig_I,px_mat,px_mat_t,py_mat,...
    py_mat_t,pxx_mat,pxx_mat_t,pxy_mat,pxy_mat_t,pyy_mat,pyy_mat_t,...
    slicel,im_size,rotpadx,rotpady,trans_slice_t,homoz_rot,...
    homoz_rot_w,bc,pose_sub_ind)
% KT_gen_convol(p) = [(omega(1)*K_mat'+omega(2)*px_mat'*K_mat'*px_mat+omega(2)*py_mat'*K_mat'*py_mat+...
%     omega(3)*pxx_mat'*K_mat'*pxx_mat+omega(3)*pxy_mat'*K_mat'*pxy_mat+...
%     omega(3)*pyy_mat'*K_mat'*pyy_mat)](p);

pOx = reshape(px_mat*Orig_I,im_size);
pOy = reshape(py_mat*Orig_I,im_size);
pOxx = reshape(pxx_mat*Orig_I,im_size);
pOxy = reshape(pxy_mat*Orig_I,im_size);
pOyy = reshape(pyy_mat*Orig_I,im_size);

Orig_I = reshape(Orig_I,im_size);
Rim = omega(1)*KT_gen_conv_spv(slicel,im_size,rotpadx,rotpady, Orig_I, trans_slice_t,homoz_rot,homoz_rot_w,bc, pose_sub_ind)+...
    omega(2)*px_mat_t*KT_gen_conv_spv(slicel,im_size,rotpadx,rotpady, pOx, trans_slice_t,homoz_rot,homoz_rot_w,bc, pose_sub_ind)+...
    omega(2)*py_mat_t*KT_gen_conv_spv( slicel,im_size,rotpadx,rotpady, pOy, trans_slice_t,homoz_rot,homoz_rot_w,bc, pose_sub_ind)+...
    omega(3)*pxx_mat_t*KT_gen_conv_spv( slicel,im_size,rotpadx,rotpady, pOxx, trans_slice_t,homoz_rot,homoz_rot_w,bc, pose_sub_ind)+...
    omega(3)*pxy_mat_t*KT_gen_conv_spv( slicel,im_size,rotpadx,rotpady, pOxy, trans_slice_t,homoz_rot,homoz_rot_w,bc, pose_sub_ind)+...
    omega(3)*pyy_mat_t*KT_gen_conv_spv( slicel,im_size,rotpadx,rotpady, pOyy, trans_slice_t,homoz_rot,homoz_rot_w,bc, pose_sub_ind);
Rim = 2*Rim;
end