function Rim = KTK_gen_convol_spv(omega,Orig_I,alpha,px_mat,px_mat_t,py_mat,...
    py_mat_t,pxx_mat,pxx_mat_t,pxy_mat,pxy_mat_t,pyy_mat,pyy_mat_t,...
    slicel,im_size,rotpadx,rotpady,homoz_rot,homoz_rot_w,...
    trans_slice,trans_slice_t,bc,pose_sub_ind)
% temp = K_mat'*K_mat;
% KTK_gen_convol(p) = [2*(omega(1)*temp+omega(2)*px_mat_t*temp*px_mat+omega(2)*py_mat_t*temp*py_mat+...
%     omega(3)*pxx_mat_t*temp*pxx_mat+omega(3)*pxy_mat_t*temp*pxy_mat+omega(3)*pyy_mat_t*temp*pyy_mat+...
%     alpha*px_mat_t*px_mat+alpha*py_mat_t*py_mat)](p);
pOx = reshape(px_mat*Orig_I,im_size);
pOy = reshape(py_mat*Orig_I,im_size);
pOxx = reshape(pxx_mat*Orig_I,im_size);
pOxy = reshape(pxy_mat*Orig_I,im_size);
pOyy = reshape(pyy_mat*Orig_I,im_size);
Orig_I = reshape(Orig_I,im_size);

Rim = omega(1)*KTK_gen_conv_spv(slicel,im_size,rotpadx,rotpady,Orig_I,homoz_rot,homoz_rot_w,trans_slice,trans_slice_t,bc,pose_sub_ind)+...
    omega(2)*px_mat_t*KTK_gen_conv_spv(slicel,im_size,rotpadx,rotpady,pOx,homoz_rot,homoz_rot_w,trans_slice,trans_slice_t,bc,pose_sub_ind)+...
    omega(2)*py_mat_t*KTK_gen_conv_spv(slicel,im_size,rotpadx,rotpady,pOy,homoz_rot,homoz_rot_w,trans_slice,trans_slice_t,bc,pose_sub_ind)+...
    omega(3)*pxx_mat_t*KTK_gen_conv_spv(slicel,im_size,rotpadx,rotpady,pOxx,homoz_rot,homoz_rot_w,trans_slice,trans_slice_t,bc,pose_sub_ind)+...
    omega(3)*pxy_mat_t*KTK_gen_conv_spv(slicel,im_size,rotpadx,rotpady,pOxy,homoz_rot,homoz_rot_w,trans_slice,trans_slice_t,bc,pose_sub_ind)+...
    omega(3)*pyy_mat_t*KTK_gen_conv_spv(slicel,im_size,rotpadx,rotpady,pOyy,homoz_rot,homoz_rot_w,trans_slice,trans_slice_t,bc,pose_sub_ind)+...
    alpha*px_mat_t*pOx(:)+alpha*py_mat_t*pOy(:);
Rim = 2*Rim;
end